spring:
  config:
    activate:
      on-profile: dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/tuge?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: ${MYSQL_PASSWORD:1234}
  data:
    redis:
      host: ${REDIS_HOST:123.57.181.126}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:123456}
